import { AppState, UserProfile } from '../types';

export const USERS: Record<string, UserProfile> = {
  selin: {
    id: 'selin',
    name: 'Selin',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7_bqVomRejqHOrlgKZbhVPBtefdBhqU_cSCTwENriRLaZoS3pWGi_u2DGYKOfNYyjJK9_RzcFEa42pFinpWAdYdLIeCQGw95HuRJAeG6OL3-S32dElaMsm7obBhSQD-rXIw8DekaeJHQZqC-Ksk2Ucpo8TOU8RIBvLtCAzRpfGyub9YGHtNY2v5TV4P8E6N2MCBRap8Yjcx_2SiyJPhgpRIRrsissCxbXOnBHpUE4pWwD7TYfvxFD',
    emoji: '🌿',
    color: '#785745',
    role: 'partner_1',
  },
  mert: {
    id: 'mert',
    name: 'Mert',
    avatar: '', // Fallback to cozy illustrated avatar component
    emoji: '☕',
    color: '#405d47',
    role: 'partner_2',
  },
};

export const INITIAL_STATE: AppState = {
  currentUserId: 'mert', // default active in demo, easily switched to selin
  patiBalance: 120,
  cat: {
    name: 'Miso',
    satiety: 75,
    happiness: 85,
    energy: 60,
    isSleeping: false,
    lastUpdated: Date.now(),
    lastFedTime: Date.now() - 1000 * 60 * 45, // 45 min ago
    lastPetTime: Date.now() - 1000 * 60 * 15,
  },
  settings: {
    catName: 'Miso',
    soundEnabled: false,
    reducedMotion: false,
    roomCode: 'PATI-7429',
    isSpaceLocked: true, // Exactly two people (Selin & Mert)
    mode: 'demo',
  },
  careLogs: [
    {
      id: 'log-1',
      actorName: 'Mert',
      actorColor: '#405d47',
      emoji: '🥣',
      actionText: "Miso'ya mama verdi.",
      timeAgo: 'Bugün 14:20',
      timestamp: Date.now() - 1000 * 60 * 40,
      rewardPati: 10,
    },
    {
      id: 'log-2',
      actorName: 'Selin',
      actorColor: '#785745',
      emoji: '🐾',
      actionText: "Miso'yu taradı ve sevdi.",
      timeAgo: 'Dün 21:05',
      timestamp: Date.now() - 1000 * 60 * 60 * 15,
    },
    {
      id: 'log-3',
      actorName: 'Mert',
      actorColor: '#161d19',
      emoji: '💧',
      actionText: 'Su kabını tazeledi.',
      timeAgo: 'Dün 18:30',
      timestamp: Date.now() - 1000 * 60 * 60 * 20,
    },
  ],
  notes: [
    {
      id: 'note-1',
      title: 'Film adayı',
      body: 'Bunu listeye ekledim, seçimi sana bırakıyorum 👀',
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      color: '#F4F7F2',
      isPinned: true,
      createdAt: Date.now() - 1000 * 60 * 120, // 2h ago
      tag: 'Film Önerisi',
      snippet: {
        type: 'movie',
        title: 'Past Lives (2023)',
        subtitle: 'Sessiz, sakin bir akşam için',
        icon: 'movie',
      },
      reactions: [
        { emoji: '😄', users: ['mert'] },
        { emoji: '👀', users: ['selin', 'mert'] },
        { emoji: '🐾', users: ['selin'] },
      ],
    },
    {
      id: 'note-2',
      title: 'Küçük hatırlatma',
      body: 'Kediye mama verdim. İkinci kahvaltı için seni kandırmasın. Gözlerini kocaman açıp mama kabının önünde masumca otursa bile tok :)',
      authorId: 'mert',
      authorName: 'Mert',
      authorEmoji: '☕',
      color: '#FCF8F2',
      isPinned: true,
      createdAt: Date.now() - 1000 * 60 * 180, // today 11:30
      tag: 'Önemli Mama Alarmı',
      snippet: {
        type: 'task',
        title: 'Tavuklu Yaş Mama',
        subtitle: 'Tamamlandı ✓',
        icon: 'soup_kitchen',
      },
      reactions: [
        { emoji: '😄', users: ['selin', 'mert'] },
        { emoji: '🐾', users: ['selin', 'mert'] },
      ],
    },
    {
      id: 'note-3',
      title: 'Kahve konusu',
      body: "Müsait bir gün Kadıköy'deki yeni yeri deneyelim mi? Çatı katında küçük bir kış bahçesi varmış, tam kitap okumalık.",
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      color: '#F7F5FC',
      isPinned: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 24, // Dün 18:40
      tag: 'Buluşma Fikri',
      snippet: {
        type: 'place',
        title: 'Köz & Yaprak Coffee House, Moda',
        subtitle: 'Sessiz ve sakin saatler',
        icon: 'local_cafe',
      },
      reactions: [
        { emoji: '☕', users: ['selin', 'mert'] },
        { emoji: '👀', users: ['mert'] },
      ],
    },
    {
      id: 'note-4',
      title: "Miso'nun yeni favorisi",
      body: 'Kutuyu atmadım, içine girip uyumaya bayıldı. Minderi boşuna almış olabiliriz :) Fotoğrafını odaya da astım.',
      authorId: 'mert',
      authorName: 'Mert',
      authorEmoji: '☕',
      color: '#FCF8F2',
      isPinned: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 48, // 2 gün önce
      tag: 'Kedi Günlüğü',
      snippet: {
        type: 'quote',
        title: '📦 Karton kutu > 400 liralık ortopedik yatak',
        subtitle: 'Miso onaylı konfor',
      },
      reactions: [
        { emoji: '😄', users: ['selin', 'mert', 'misofan'] },
        { emoji: '🐾', users: ['selin', 'mert'] },
      ],
    },
    {
      id: 'note-5',
      title: 'İyi çalışmalar ✨',
      body: 'Bugünkü toplantı maratonunun kolay geçmesini dilerim. Akşam kediye tüylerini tarama sırası bende!',
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      color: '#F4F7F2',
      isPinned: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 72, // 3 gün önce
      tag: 'Sakin Mola',
      reactions: [
        { emoji: '☕', users: ['mert'] },
        { emoji: '🐾', users: ['selin'] },
      ],
    },
  ],
  wishlist: [
    {
      id: 'wish-1',
      title: 'Birlikte bir komedi filmi seçelim',
      description: "Hafta sonu için rahat, yormayan bir şeyler. Patlamış mısır bizden, battaniye Miso'dan.",
      category: 'film',
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      isCompleted: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 24,
      likes: ['mert'],
    },
    {
      id: 'wish-2',
      title: 'Yeni bir kahveci deneyelim',
      description: 'Moda tarafındaki fırınlı kafe; tarçınlı çörekleri çok övülmüş. Sessiz bir saatte uğrarız.',
      category: 'kahve',
      authorId: 'mert',
      authorName: 'Mert',
      authorEmoji: '☕',
      isCompleted: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 72,
      likes: ['selin'],
    },
    {
      id: 'wish-3',
      title: 'İki kişilik bir oyun bulalım',
      description: "Co-op indie oyun önerilerine açığım. 'It Takes Two' tarzı veya daha sakin bulmaca olabilir.",
      category: 'oyun',
      authorId: 'mert',
      authorName: 'Mert',
      authorEmoji: '☕',
      isCompleted: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 96,
      likes: [],
    },
    {
      id: 'wish-4',
      title: "Miso'nun odasına yeni bir minder alalım",
      description: 'Pati puanımız 120 oldu, eşyalar sekmesine birlikte bakalım. Hasır sepet de çok tatlıydı!',
      category: 'diger',
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      isCompleted: false,
      createdAt: Date.now() - 1000 * 60 * 60 * 120,
      likes: ['mert'],
    },
    {
      id: 'wish-5',
      title: "Miso'ya isim seçtik",
      description: 'Birlikte karar verdik, artık resmi adı Miso.',
      category: 'diger',
      authorId: 'selin',
      authorName: 'Selin',
      authorEmoji: '🌿',
      isCompleted: true,
      completedAt: Date.now() - 1000 * 60 * 60 * 168,
      createdAt: Date.now() - 1000 * 60 * 60 * 200,
      likes: ['mert', 'selin'],
    },
    {
      id: 'wish-6',
      title: 'İlk kahve sohbeti',
      description: 'Günün yorgunluğunu atan ilk uzun sohbet.',
      category: 'kahve',
      authorId: 'mert',
      authorName: 'Mert',
      authorEmoji: '☕',
      isCompleted: true,
      completedAt: Date.now() - 1000 * 60 * 60 * 336,
      createdAt: Date.now() - 1000 * 60 * 60 * 340,
      likes: ['mert', 'selin'],
    },
  ],
  shopItems: [
    {
      id: 'item-cloud-bed',
      name: 'Bulut Minder',
      description: "Miso'nun öğle uykuları için yumuşacık keten minder.",
      category: 'minderler',
      price: 80,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRnPpZCCexLv71gVLbx5yOZ3Ebu4O-H03-CTUy9peBPpDo-ehca3nv-VydaAD0bB4VscpMgc53Vzz93Aq_5pEhyoQyy_abh1XMr2nkYVwURheeeiFA3jN0kfnI2SouldAj3uky7vDaURPhAU2rpQ17RIx82W7SZKpZqHG7ROzhi2dEYQg6BKK0kN-w_QYZo7I9KPSK3ykxjSlBtqpLrk5BddjQyAKzKLX7R6-p3IcvdSzcNmzapEG0',
      fallbackEmoji: '☁️',
      isOwned: true,
      isPlaced: true,
      badge: 'Odada Aktif',
    },
    {
      id: 'item-fish-toy',
      name: 'Balık Oyuncak',
      description: 'Kedi nanesi kokulu, el yapımı çıngıraklı balık.',
      category: 'oyuncaklar',
      price: 40,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCg9cTnnZiu1vz3YFQ_lZ-imobpsq7Sx-rney8-W08RkXO0eI7lGb7dffnckrEevVFotNlJ85u4JVyNLk7XJAIxXbLjsUq-GgbsK774pgUUCE6BWJHboQA_1qqJzBam6GMtVWfKjoN7S6_C2OLOmIDu-oD6wOnlg2XqPZx41geGMR-_rCvsUQ0RV_GUzMwmDptkJ1mexYALGtzYpTpjYWcNzXZ_ZUHLVWpj-waWwreIuuVfpnjfj4sx',
      fallbackEmoji: '🐟',
      isOwned: true,
      isPlaced: false,
      badge: 'Sandıkta',
    },
    {
      id: 'item-ceramic-bowl',
      name: 'Seramik Mama Kabı',
      description: 'Ergonomik yüksek ayaklı, temizliği kolay el yapımı seramik.',
      category: 'kaplar',
      price: 60,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBTl1SWaKnXGE091pEHOaDlOH-uIYiF4waOSA9VYPmfg44__uvAf67qiy_7bfNyMfx0B1iP8NxPGqSWlYgaoPJSZFALk-YFlZt_2FBeQr6D7G9HDLHdzdldSdpleQhhIYZhg-Uujz0VcjNwJCEM-BlzIukb322kS81Ltv7XUEV4cDDntABkzHQgO1DkCDOaeOwx9QD6INkjWUadunx2bPn-NrLee4A0sxlTaMQ1GpT1hKSAF_JGeMNM',
      fallbackEmoji: '🥣',
      isOwned: false,
      isPlaced: false,
      badge: 'Popüler',
    },
    {
      id: 'item-snake-plant',
      name: 'Küçük Saksı / Paşa Kılıcı',
      description: 'Odanın havasını tazeleyen, kedilere zararsız yeşil saksı.',
      category: 'susler',
      price: 50,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAt5qDdB1F4ioAfL24bfV2fHpF_G1aXQngA_R4-YNhLNFqJAnoBucQ4feXVARzf3NWhxIxlYYdSsaKWKm0OcmtO8A6m3xUbuSZcrCAaWB05LWlvJKTuVr3RZ9YFuxseB7xzCp8tPZAD2NUYL-zIhTm9PrqYlaP_q84EGbdnSC6fkTbhmJpexZYttLTtGfs10GnsIieVJ2Vpcd61a9rRx1uiFdgo7JGipHQ9O-pltXv7TwmSIlWZ4wbC',
      fallbackEmoji: '🪴',
      isOwned: false,
      isPlaced: false,
      badge: 'Kedi Dostu',
    },
    {
      id: 'item-scratching-post',
      name: 'Ahşap Tırmalama Direği',
      description: 'Doğal sisal ipiyle sarılmış, tırnak törpüleme alanı.',
      category: 'susler',
      price: 150,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfBzoywwt_7CZRQAIaXy-YKrKzjjDfbS0--KHus-HBCHzVNsvoVOiD-zZhVJp119OQfuWM993XS8tenFbShDQMTSMRxlYQE3C0-q2xPJQHbrWslvi3GMTP-7dbd08Ov-TDheeunkESztiGvK3VMgf8nIQiWj92syvNpKsX7Npqx0-Nabjf6SgQS-KpV54o8bSca5HQ_swnqocTNwlv6HM0Nn1lb1pxTKB4Jd8mHkF4Ji3Fny6TA18b',
      fallbackEmoji: '🪵',
      isOwned: false,
      isPlaced: false,
      badge: 'Büyük Eşya',
    },
    {
      id: 'item-window-perch',
      name: 'Pencere Pervazı Minderi',
      description: 'Dışarıdaki kuşları izlerken sıcacık mayışma noktası.',
      category: 'minderler',
      price: 100,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgSOOQQxPQdlqhWjkWD8yHkRCAeufiSz9bAyi1ctbdwo4JSQJToKBMY2bTQlczraT_PJ8XCpgy49k-OcGvpcgCg36PEiaomKSOaShhw2TUbvao0m8Di7EJiPPe7SQfGZQCZqfVmokvTbSp07ki6jG_V-sY7QSXYHzQErfQiny7Dpku3WArETjiBDzP_2v2L9hykCv9d9LQsYoQZeagLC9pC5tElTDsJziNFDQzAUSYR2ZdpW55ujL-',
      fallbackEmoji: '☀️',
      isOwned: false,
      isPlaced: false,
      badge: 'Güneş Alanı',
    },
  ],
};

export const MISO_THOUGHTS = [
  'Biri sana not bırakmış. Ben okumadım… galiba.',
  'İlgi sırası bende.',
  'Bu film listesi uzuyor ama izleyen yok.',
  'Benim mamam tamam. Siz kahve işini hallettiniz mi?',
  'Güneş tam buraya vuruyor, kıpırdayamam.',
  'Bugün ikiniz de çok yoruldunuz, biraz dinlenin.',
  'Kutunun içinde uyumak dünyanın en tatlı şeyi.',
  'Pati puanları birikiyor, odaya yeni saksı yakışır.',
];
